# Sayes rem to change title and description
title: Sayes Sample
description: A sample demonstration for sayes
show_downloads: true

# Sayes rem to change baseurl and url
baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://Sanxinglaopa.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme:  # leave it empty

#Sayes Update your social profile
# social #update social profile
author: Sayes
image: /thumbnail-jumbo.png
twitter:
  username: sayes

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
